name: Docker Publish to Hub

# Pokreće se SAMO kada se kreira novi Git tag
on:
  push:
    tags:
      # Reaguje na tagove poput v1.0.0, v2.5.1
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    
    # Dozvole su potrebne za čitanje koda
    permissions:
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          # Potrebno za pravilno čitanje Git taga
          fetch-depth: 0

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          # Očekuje se da u repo secrets postoje:
          # DOCKER_USERNAME (npr. m1l1)
          # DOCKER_TOKEN   (Docker Hub Access Token)
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Extract metadata (tags) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          # Format image-a: <username>/logo, npr: m1l1/logo
          images: ${{ secrets.DOCKER_USERNAME }}/logo
          tags: |
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_latest}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha 
          cache-to: type=gha,mode=max

